apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarization
  labels:
    app: binarization
spec:
  replicas: 3
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: binarization
  template:
    metadata:
      labels:
        app: binarization
    spec:
      containers:
      - name: binarization
        image: jingchaoluan/binarization:v1
        ports:
        - containerPort: 80
        resources:
        #  limits:
        #    cpu: "1"
          requests:
            cpu: "0.5"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: binarization
  labels:
    app: binarization
spec:
  type: NodePort
  selector:
    app: binarization
  ports:
    - port: 80
      nodePort: 40001
      targetPort: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: binarization-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: binarization
  minReplicas: 1
  maxReplicas: 10
#  targetCPUUtilizationPercentage: 80 # can only be used in version 'v1'

### Following metrics can be used in version 'v2beta1'
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
#    - type: Pods
#      pods:
#        metricName: packets-per-second
#        targetAverageValue: 100
#    - type: Object
#      object:
#        metricName: requests-per-second
#        target:
#          apiVersion: extensions/v1beta1
#          kind: Ingress
#          name: main-route
#        targetValue: 1k
