version: '3'

services:
    binarization:
        image: jingchaoluan/ocropy_binarization_ms:v1
        deploy:
            replicas: 2
        ports:
            - '8001:8001'
    segmentation:
        image: jingchaoluan/ocropy_segmentation_ms:v1
        deploy:
            replicas: 2
        ports:
            - '8002:8002'
    recognition:
        image: jingchaoluan/ocropy_recognition_ms:v1
        deploy:
            replicas: 2
        ports:
            - '8003:8003'
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
