version: '3'

services:
    binarization:
        build: ./BinarizationService
        ports:
            - '8001:8001'
    segmentation:
        build: ./SegmentationService
        ports:
            - '8002:8002'
    recognition:
        build: ./RecognitionService
        ports:
            - '8003:8003'
